config/routes.rb
Rails.application.routes.draw do

  root 'profiles#index'
  resources :profiles
  devise_for :users

  resources :products do
    resources :reviews
    resources :photos
  end

  resources :conversations do
    resources :messages
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%d/%m/%y at %R%Z")
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_conversation

  def index
    @messages = @conversation.messages
    if @messages.length > 10
      @over_ten = true
      @messages = @messages [-10..-1]
    end

    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end

    if @messages.last
      if @messages.last.user_id != current_user.id
        @messages.last.read = true;
      end
    end

    @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

  private
    def set_conversation
      @conversation = Conversation.find(params[:conversation_id])
    end

    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body, :conversation_id, :user_id, :read)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for [@conversation, @message] do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
  <div>
    <%= f.submit "Add Reply", class: "ui blue labeled submit icon button" %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<%= link_to "< Back To Conversations", conversations_path %>

<% if @over_ten %>
  <%= link_to "Show Previous", "?m=all" %>
<% end %>

<div class="ui segment">
  <% @messages.each do |message| %>
    <% if message.body %>
    <% user = User.find(message.user_id) %>
    <div class="item">
      <div class="content">
        <div class="header">
          <strong><%= user.profile.username %></strong>
                  @ <%= message.message_time %>
        </div>
        <div class="list">
          <div class="item">
            <i class="right triangle icon"></i>
            <%= message.body %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

<%= render 'form' %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>Conversation:</strong>
  <%= @message.conversation %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user %>
</p>

<p>
  <strong>Read:</strong>
  <%= @message.read %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>